version: "3"
services:
  php:
    image: "registry.cn-shenzhen.aliyuncs.com/zed/php:7.2-fpm-alpine3.8"
    ports:
      - 9501:9501
    volumes:
      - ./:/var/www/html
    links:
      - redis
  redis:
    image: "redis:3-alpine"
    ports:
      - 6379:6379